#+TITLE: Productivity and Applications
#+AUTHOR: Jay Kamat
#+EMAIL: jaygkamat@gmail.com
#+DATE: <2017-01-22 Sun>
#+OPTIONS: auto-id:t

* Why Even Bother?
:PROPERTIES:
:CUSTOM_ID: h:xdhd2as0gyh0
:END:

I'm really picky about the applications I use, mainly to make sure I'm
maximizing my productivity.

Vim was the first example I had of how much productivity matters (at least to a
programmer). A common action such as 'append text to the current line' is
/extremely/ common and saving 5 seconds or so on it adds up to a /lot/ of saved
time in the long run.

* Core
:PROPERTIES:
:CUSTOM_ID: h:3uod2as0gyh0
:END:

In general, I look for 3 things in any application before I begin relying on it.

Is the program:
1. Stable
2. Customizable
3. Lightweight

I'll talk about a few instances where I switched applications to give you a
better idea of what I'm talking about.

** Stability
:PROPERTIES:
:CUSTOM_ID: h:8zvd2as0gyh0
:END:

Stability is important for obvious reasons.
If a program crashes, freezes, or stops working, you loose productivity in the
worst way possible, leaving you unable to work at all. Using older versions of
software can help with this as well, but occasionally there is software that is
completely unusable due to it's instability, which I can never use.

An example of this is ~apvlv~, which I couldn't get running without segfaults
(even on multiple environments). Even older versions seemed to have the same
issue for me. Despite fitting well into my workflow otherwise, I'm unable to use
~apvlv~ due to stability.

** Customizability
:PROPERTIES:
:CUSTOM_ID: h:1b2e2as0gyh0
:END:

Software that is customizable helps with productivity because it makes it easy
to change the program to do exactly what you need with the least amount of
effort on your end. Customizable software also lends itself extremely well to
automation, which improves productivity immensely.

I used to use GNOME as my primary desktop environment/window manager, until
GNOME 3 was released. GNOME 3 is nice in terms of ease of use and it is very
well polished, but it lacks customizability. It's very hard to get the /exact/
behavior you want on GNOME 3, and that's why I ditched it for KDE at the time.

** Being Lightweight
:PROPERTIES:
:CUSTOM_ID: h:d98e2as0gyh0
:END:

Minimalist applications lend to productivity, simply because they are doing
less. Especially when on limited hardware, lightweight applications end up being
much faster to use. Minimalist software also has the added benefit that you can
reasonably understand the entire program quickly, and modify it to suit your
needs, which adds immense customizability.

For me, I ended up ditching Eclipse because it was much too heavy. It has a
immense amount of features, which is nice, but Eclipse on my computer was
unbearably slow when compared to a simple text editor. While the features of an
IDE are very appealing, I can probably never go back to using one due to this
point.

* Wrapping Up
:PROPERTIES:
:CUSTOM_ID: h:0sde2as0gyh0
:END:

Hopefully this post can help you become more productive. I find that even small
changes to workflow can improve productivity immensely, and reviewing the
applications you use every day can help you have more free time in the future!

* Navigation
:PROPERTIES:
:CUSTOM_ID: h:vcje2as0gyh0
:END:

#+BEGIN_SRC emacs-lisp :exports results :results raw
(gen-prev-next)
#+END_SRC
